### ISSUE TITLE
Generate the json schema for config file

### ISSUE THREAD

**Issue by antonlisovenko** [loft-sh/devspace#1652] opened 2021-09-15 20:29 UTC
Hi guys.

Would be great if devspace provided the json schema generated by the Go struct for the config. Quick googled this [https://github.com/alecthomas/jsonschema](https://github.com/alecthomas/jsonschema)

Having json schema allows to import it to an IDE and get an auto-completion/validation support while editting config.

thanks for the great product!

**Comment by FabianKramm** [comment] 2021-09-16 12:25
@antonlisovenko thanks for creating this issue! Yes, I think we could add a json schema

**Comment by leventogut** [comment] 2022-03-14 23:24
Duplicate of #1146

**Closed** 2022-11-07 15:29 UTC
Labels: kind/feature, area/config
